server:
  port: 9231


app:
  udp:
    port: 9234
    buffer-size: 65507
    thread-pool-size: 20
  device-map:
    personnel-device-id: PERSON001
    vehicle-device-id: CAR001
  geodetic:
    base-url: https://www.geodetic.gov.hk/transform/v2/


spring:
  thymeleaf:
    cache: false